spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-db
    username: postgres
    password: 1314
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
